### user1: 管理者太郎
### user2: 開発者太郎
### user3: ユーザー太郎
### パスワードは共通
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "login_id": "user1",
    "password": "password"
}

### 
GET http://localhost:8080/api/user_info

###
POST http://localhost:8080/api/logout

