openapi: '3.0.2'
info:
  title: gin-helloworld
  version: '1.0'
servers:
  - url: http://localhost:8080/api
paths:
  /login:
    post:
      tags: ['login']
      description: ログインAPI
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login_request'
        required: true
      responses: 
        '200':
          description: OK
  /logout:
    post:
      tags: ['logout']
      description: ログアウトAPI
      responses:
        '200':
          description: OK
  /user_info:
    get:
      tags: ['users', 'developer', 'admin', 'user']
      description: セッション上のユーザー情報取得API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/user_info'



components:
  schemas:
    login_request: 
      type: object
      properties:
        login_id:
          type: string
        password:
          type: string
          format: password
      required:
        - "login_id"
        - "password"
    user_info:
      type: object
      properties:
        name: 
          type: string
          example: サンプル太郎
        role: 
          type: string
          example: ユーザー
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer