// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package openapi

// LoginRequest defines model for login_request.
type LoginRequest struct {
	LoginId  *string `json:"login_id,omitempty"`
	Password *string `json:"password,omitempty"`
}

// UserInfo defines model for user_info.
type UserInfo struct {
	Name *string `json:"name,omitempty"`
	Role *string `json:"role,omitempty"`
}

// GetUserInfoParams defines parameters for GetUserInfo.
type GetUserInfoParams struct {
	// Token Bearerトークン
	Token string `form:"token" json:"token"`

	// Id セッションの実装が完了するまでの一時的なパラメータ(非推奨)
	Id *int `form:"id,omitempty" json:"id,omitempty"`
}

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginRequest
